#!/bin/bash
# (C) 2018 - Esteban D.Dortta
# ydownloader
# It uses the same config file that yprojectguardian uses
# This script will:
#   1) Check if there is an internet connection pinging 8.8.8.8
#   2) Compares current version with remote one
#   3) If differs (for up or down), downloads to 'backup' folder


OVERWRITE=0
CONFIG="yproject.ini"

while getopts c:o:h option; do 
  case "${option}" 
  in 
    h) 
      echo "  "
      echo "$0"
      echo "(C) 2018 Esteban D.Dortta"
      echo "  Project downloader"
      echo "  This script helps you to keep your project distribution up-to-date"
      echo "    -h shows this help"
      echo "    -c config file (defaults to ./yproject.ini)"
      echo "    -o after download, if overwrites or create application folder"
      echo "  "
      exit 0
      ;; 
    o) 
      OVERWRITE="1"
      ;;
    c) 
      CONFIG="${OPTARG}"
      ;;
  esac 
done 



if [ -f "$CONFIG" ]; then
  source=$(awk -F "=" '/source/ {print $2}' $CONFIG | sed -e 's/^ *//' -e 's/ *$//')
  id=$(awk -F "=" '/id/ {print $2}' $CONFIG | sed -e 's/^ *//' -e 's/ *$//')
  backup=$(awk -F "=" '/backup/ {print $2}' $CONFIG | sed -e 's/^ *//' -e 's/ *$//')
  folder=$(awk -F "=" '/folder/ {print $2}' $CONFIG | sed -e 's/^ *//' -e 's/ *$//')
  license=$(awk -F "=" '/license/ {print $2}' $CONFIG | sed -e 's/^ *//' -e 's/ *$//')

  if [ ! -z "$backup" ]; then
    if [ ! -d "$backup" ]; then
      echo "Creating $backup..."
      mkdir "$backup"
    fi

    if [ -d "$backup" ]; then 
      url="$source/check/$id/$license";
      wget -O "/tmp/$id.json" $url
    else
      echo "Folder '$backup' not found"
      exit 1
    fi
  fi

else
  echo " "
  echo "$0"
  echo "(C) 2018 Esteban D.Dortta"
  echo "This script will check current version of a local copy of a project against the public one."
  echo "If it differs, it will download and overwrite the 'backup' folder"
  echo "* $CONFIG config file not found!"
  echo "Use $0 -h to more help"
  echo " "
fi